-- Generated by scripts/extract.ts — do not edit by hand
BEGIN;
TRUNCATE rtus, tenants, buildings, utilities, polygons, app_settings RESTART IDENTITY CASCADE;
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (1, 'Dixie Business Park (x 34)', '1850 Derry Road East', '65155', 43.681783, -79.66556, '48,030', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (2, 'Dixie Business Park (x 34)', '1645 Bonhill Road', '65171/50200', 43.66613, -79.6532806, '51,814', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (3, 'Dixie Business Park (x 34)', '1680 Courtneypark Drive', '65172', 43.6664746, -79.6538068, '51,318', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (4, 'Dixie Business Park (x 34)', '1695 Bonhill Road', '65173', 43.6669454, -79.6521422, '28,297', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (5, 'Dixie Business Park (x 34)', '1700 Courtneypark Drive', '65174', 43.6673761, -79.6528563, '37,512', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (6, 'Dixie Business Park (x 34)', '1745 Bonhill Road', '65175', 43.6676523, -79.6513419, '36,562', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (7, 'Dixie Business Park (x 34)', '1750 Courtneypark Drive', '65176', 43.6680788, -79.6520553, '48,689', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (8, 'Dixie Business Park (x 34)', '1775 Bonhill Road', '65177', 43.66839, -79.65048, '36,675', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (9, 'Dixie Business Park (x 34)', '1800 Courtneypark Drive', '65178', 43.6688257, -79.6512072, '43,281', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (10, 'Dixie Business Park (x 34)', '1820 Courtneypark Drive', '65179', 43.6692923, -79.6500963, '88,185', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (11, 'Dixie Business Park (x 34)', '1840 Courtneypark Drive', '65180', 43.669857, -79.649334, '99,390', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (12, 'Dixie Business Park (x 34)', '1870 - 1880 Courtneypark Drive', '65181', 43.6708345, -79.649369, '60,943', 'Dixie 1 (x 12)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (13, 'Dixie Business Park (x 34)', '1495 Bonhill Road', '65186', 43.6618562, -79.654349, '33,597', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (14, 'Dixie Business Park (x 34)', '1535 Meyerside Drive', '65187', 43.661262, -79.654392, '48,879', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (15, 'Dixie Business Park (x 34)', '1577 Meyerside / 1500 Bonhill', '65188', 43.6630604, -79.6517072, '140,986', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (16, 'Dixie Business Park (x 34)', '1633 - 1655 Meyerside Drive', '65189', 43.6634023, -79.651249, '95,740', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (17, 'Dixie Business Park (x 34)', '1675 - 1705 Meyerside Drive', '65190', 43.664417, -79.650593, '96,420', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (18, 'Dixie Business Park (x 34)', '1715 Meyerside Drive', '65191', 43.6654539, -79.6495231, '51,077', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (19, 'Dixie Business Park (x 34)', '1745 Meyerside Drive', '65192', 43.6659982, -79.6488819, '50,998', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (20, 'Dixie Business Park (x 34)', '1775 Meyerside Drive', '65193', 43.666525, -79.6482917, '38,486', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (21, 'Dixie Business Park (x 34)', '1795 Meyerside Drive', '65194', 43.6669308, -79.6478095, '49,775', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (22, 'Dixie Business Park (x 34)', '1815 Meyerside Drive', '65195', 43.667501, -79.647294, '38,427', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (23, 'Dixie Business Park (x 34)', '1835 Meyerside Drive', '65196', 43.6679951, -79.6470234, '49,298', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (24, 'Dixie Business Park (x 34)', '1865 Meyerside Drive', '65197', 43.6684215, -79.646147, '49,248', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (25, 'Dixie Business Park (x 34)', '6350 Netherhart / 1885 Meyerside Drive', '65198', 43.668977, -79.6455393, '64,383', 'Dixie 2 (x 13)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (26, 'Dixie Business Park (x 34)', '1550 Courtneypark Drive', '65201', 43.6645687, -79.6556634, '73,621', 'Dixie 4 (x 4)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (27, 'Dixie Business Park (x 34)', '1555 Bonhill Road', '65202', 43.6626427, -79.6550847, '36,259', 'Dixie 4 (x 4)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (28, 'Dixie Business Park (x 34)', '1600 Courtneypark Drive', '65203', 43.6652227, -79.6546685, '91,711', 'Dixie 4 (x 4)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (29, 'Dixie Business Park (x 34)', '6325 Dixie Road', '65204', 43.6622005, -79.6557365, '36,234', 'Dixie 4 (x 4)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (30, 'Dixie Business Park (x 34)', '6915 Dixie Road', '53810', 43.674184, -79.670574, 'New Development', 'Single (x 5)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (31, 'Dixie Business Park (x 34)', '7311 Kimbel Street', '53850', 43.7035128, -79.6575828, '111,603', 'Single (x 5)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (32, 'Dixie Business Park (x 34)', '1590 South Gateway Road', '53845', 43.6346457, -79.6114408, '195,038', 'Single (x 5)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (33, 'Dixie Business Park (x 34)', '1700 Derry Road', '53810', 43.6794145, -79.6686856, '114,132', 'Single (x 5)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (34, 'Dixie Business Park (x 34)', '6950 Menkes Drive', '53810', 43.6790562, -79.6693417, 'New Development', 'Single (x 5)', 'Evelyn Lu', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (35, 'East Business Park (x 22)', '55 Interchange Way', '51902', 43.78988, -79.52739, '122,037', 'Interchange Industrial (x 2)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (36, 'East Business Park (x 22)', '7540 Jane Street', '51901', 43.7904617, -79.5252241, '120,000', 'Interchange Industrial (x 2)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (37, 'East Business Park (x 22)', '101 Exchange Avenue', '51800', 43.786354, -79.532583, '61,169', 'Interchange Office (x 1)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (38, 'East Business Park (x 22)', '100 Leek Crescent', '50450', 43.861112, -79.38184, '69,802', 'Richmond Hill Business Park (x 7)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (39, 'East Business Park (x 22)', '25 Leek Crescent', '50451', 43.862352, -79.379456, '75,421', 'Richmond Hill Business Park (x 7)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (40, 'East Business Park (x 22)', '35 Leek Crescent', '50452', 43.862373, -79.377969, '35,405', 'Richmond Hill Business Park (x 7)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (41, 'East Business Park (x 22)', '45 Mural Street', '50453', 43.860079, -79.383424, '73,241', 'Richmond Hill Business Park (x 7)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (42, 'East Business Park (x 22)', '50 Leek Crescent', '50454', 43.862471, -79.37665, '105,185', 'Richmond Hill Business Park (x 7)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (43, 'East Business Park (x 22)', '56 Leek Crescent', '50455', 43.861601, -79.376034, '60,780', 'Richmond Hill Business Park (x 7)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (44, 'East Business Park (x 22)', '85 Leek Crescent', '50455', 43.861185, -79.38008, '50,581', 'Richmond Hill Business Park (x 7)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (45, 'East Business Park (x 22)', '39 Steelcase Road West (Blg 1)', '53790', 43.8181893, -79.3540143, '169,230', 'The Steelcase (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (46, 'East Business Park (x 22)', '11 Steelcase Road West (Blg 2)', '53790', 43.818621, -79.351799, '192,052', 'The Steelcase (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (47, 'East Business Park (x 22)', '60 Idema Road  (Blg 3)', '53790', 43.817166, -79.35192, '260,290', 'The Steelcase (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (48, 'East Business Park (x 22)', '145 Carrier Drive', '53770', 43.740873, -79.615643, '551,264', 'The Carrier (x 1)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (49, 'East Business Park (x 22)', '5455 Ashburn Road', '53831', 43.9403444, -78.9677354, '279,216', 'The Ashburn (x 1)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (50, 'East Business Park (x 22)', '(8925-old) 8945 Torbram Road', '53780', 43.734272, -79.704831, '201,832', 'The Torbram (x 1)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (51, 'East Business Park (x 22)', '130 - 146 Sparks Ave', '50600', 43.8081545, -79.3425081, '89,007', 'Victoria / Denison Business Park (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (52, 'East Business Park (x 22)', '200 - 206 Sparks Ave', '50603', 43.8080844, -79.3418209, '36,972', 'Victoria / Denison Business Park (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (53, 'East Business Park (x 22)', '250 - 256 Sparks Ave', '50605', 43.808634097723015, -79.34093437116341, '36,570', 'Victoria / Denison Business Park (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (54, 'East Business Park (x 22)', '60 Birmingham St (Blg 1)', '53731', 43.6049973, -79.5004769, '157,710', 'The Birmingham (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (55, 'East Business Park (x 22)', '160 Dwight Ave (Blg 2)', '53732', 43.606272, -79.50109, '120,671', 'The Birmingham (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (56, 'East Business Park (x 22)', '175 New Toronto St (Blg 3)', '53733', 43.607175, -79.501445, '119,393', 'The Birmingham (x 3)', 'Sylvia Zwierkowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (57, 'Meadowvale North Business Park (x 24)', '7030 Royal Bank Drive', '65111', 43.6088302, -79.7492526, '12,000', 'Halton Hills (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (58, 'Meadowvale North Business Park (x 24)', '20 Westbridge Drive', '52904', 43.557478, -79.852257, '324,708', 'Halton Hills (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (59, 'Meadowvale North Business Park (x 24)', '40 Westbridge Drive', '52905', 43.554133, -79.851118, '774,614', 'Halton Hills (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (60, 'Meadowvale North Business Park (x 24)', '6100 Kenway Drive', '50400', 43.6368278, -79.6710821, '121,773', 'Kenway Business Park (x 7)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (61, 'Meadowvale North Business Park (x 24)', '6150 Kennedy Road', '50402', 43.638072, -79.672553, '92,354', 'Kenway Business Park (x 7)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (62, 'Meadowvale North Business Park (x 24)', '6160 Kenway Drive', '50403', 43.63595, -79.67366, '141,039', 'Kenway Business Park (x 7)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (63, 'Meadowvale North Business Park (x 24)', '6175 Kenway Drive', '50404', 43.636426, -79.674878, '68,255', 'Kenway Business Park (x 7)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (64, 'Meadowvale North Business Park (x 24)', '6200 Kenway Drive', '50405', 43.6356577, -79.6753096, '78,183', 'Kenway Business Park (x 7)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (65, 'Meadowvale North Business Park (x 24)', '6270 Kenway Drive', '50406', 43.634772, -79.6772392, '127,961', 'Kenway Business Park (x 7)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (66, 'Meadowvale North Business Park (x 24)', '6300 Kenway Drive', '50407', 43.6351579, -79.6785709, '61,355', 'Kenway Business Park (x 7)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (67, 'Meadowvale North Business Park (x 24)', '150 Courtneypark', '65215', 43.633548, -79.696918, '512,947', 'Mississauga Gateway (x 2)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (68, 'Meadowvale North Business Park (x 24)', '151 Courtneypark', '65216', 43.634565, -79.698446, '143,129', 'Mississauga Gateway (x 2)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (69, 'Meadowvale North Business Park (x 24)', '320 Superior Boulevard', '50502', 43.6470589, -79.6917331, '57,932', 'Mississauga Portfolio (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (70, 'Meadowvale North Business Park (x 24)', '326 Superior Boulevard', '50503', 43.6475844, -79.6908405, '59,777', 'Mississauga Portfolio (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (71, 'Meadowvale North Business Park (x 24)', '441 Courtneypark', '50501', 43.6469708, -79.6864165, '178,893', 'Mississauga Portfolio (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (72, 'Meadowvale North Business Park (x 24)', '6950 Creditview Road', '50804', 43.6119698, -79.7406814, '106,552', 'MNBP FLEX (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (73, 'Meadowvale North Business Park (x 24)', '6975 Creditview Road', '65120', 43.6145621, -79.7428113, '144,207', 'MNBP FLEX (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (74, 'Meadowvale North Business Park (x 24)', '6990 Creditview Road', '50803', 43.6126394, -79.7450899, '153,901', 'MNBP FLEX (x 3)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (75, 'Meadowvale North Business Park (x 24)', '6774 Financial Drive', '65129', 43.609289, -79.742532, '50,085', 'MNBP Single (x 6)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (76, 'Meadowvale North Business Park (x 24)', '6820 Creditview Drive', '65128', 43.6130238, -79.7359671, '50,000', 'MNBP Single (x 6)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (77, 'Meadowvale North Business Park (x 24)', '6911 Creditview Road', '65126', 43.6132887, -79.7406739, '58,337', 'MNBP Single (x 6)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (78, 'Meadowvale North Business Park (x 24)', '6901 Creditview Road', '65126', 43.6140946, -79.7388158, '262,452', 'MNBP Single (x 6)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (79, 'Meadowvale North Business Park (x 24)', '6955 Creditview Road', '65127', 43.6161556, -79.7412143, '175,879', 'MNBP Single (x 6)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (80, 'Meadowvale North Business Park (x 24)', '6980 Creditview Road', '50901', 43.6121806, -79.7434047, '171,976', 'MNBP Single (x 6)', 'Maia Krasowski', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (81, 'Western Business Park (x 22)', '2300 Bristol Circle', '51201', 43.515572, -79.6763205, '60,370', 'Bristol / Brighton (x 4)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (82, 'Western Business Park (x 22)', '2320 Bristol Circle', '51202', 43.5164587, -79.6769601, '58,051', 'Bristol / Brighton (x 4)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (83, 'Western Business Park (x 22)', '2880 Brighton Road', '51203', 43.51513, -79.678714, '25,825', 'Bristol / Brighton (x 4)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (84, 'Western Business Park (x 22)', '2910 Brighton Road', '51204', 43.515678, -79.678188, '25,825', 'Bristol / Brighton (x 4)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (85, 'Western Business Park (x 22)', '3105 Unity Drive', '50303', 43.5386636, -79.7085232, '87,171', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (86, 'Western Business Park (x 22)', '3135 Unity Drive', '50302', 43.5377366, -79.7089615, '47,146', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (87, 'Western Business Park (x 22)', '3150 Ridgeway Drive', '50311', 43.5174654, -79.6930542, '40,721', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (88, 'Western Business Park (x 22)', '3165 Unity Drive', '50301', 43.5372836, -79.7098712, '29,744', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (89, 'Western Business Park (x 22)', '3170 Ridgeway Drive', '50311', 43.518095, -79.693828, '46,730', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (90, 'Western Business Park (x 22)', '3176 Ridgeway Drive', '50312', 43.517449, -79.694518, '39,348', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (91, 'Western Business Park (x 22)', '3180 Ridgeway Drive', '50312', 43.5176463, -79.6951259, '9,892', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (92, 'Western Business Park (x 22)', '3184 Ridgeway Drive', '50312', 43.5172236, -79.6952698, '11,398', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (93, 'Western Business Park (x 22)', '3190 Ridgeway Drive', '50312', 43.5169901, -79.6959656, '71,060', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (94, 'Western Business Park (x 22)', '3345 Laird Road', '50307', 43.5169224, -79.692202, '46,320', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (95, 'Western Business Park (x 22)', '3375 Laird Road', '50308', 43.5163737, -79.6928302, '29,639', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (96, 'Western Business Park (x 22)', '3425 Laird Road', '50309', 43.5158247, -79.693741, '68,807', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (97, 'Western Business Park (x 22)', '3495 Laird Road', '50310', 43.5162097, -79.6957417, '61,149', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (98, 'Western Business Park (x 22)', '4085 Sladeview Crescent', '50313', 43.5278323, -79.7178818, '62,323', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (99, 'Western Business Park (x 22)', '4120 Ridgeway Drive', '50306', 43.529805, -79.717464, '80,860', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (100, 'Western Business Park (x 22)', '4141 Sladeview Crescent', '50305', 43.5291815, -79.7182746, '74,918', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (101, 'Western Business Park (x 22)', '4161 Sladeview Crescent', '50304', 43.5303811, -79.7185786, '41,333', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (102, 'Western Business Park (x 22)', '4181 Sladeview Crescent', '50304', 43.531133, -79.718202, '54,047', 'Western Business Park (x 18)', 'Josh Starkey', NULL);
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (1, 1, 'RTU-01', 'Building: 1850 Derry Road East
System: Roof Top Units
Description: RTU-01
Suite: Single Tenant
Model: GBC060AWEMB0000
Serial: 23254733PA
Make: TRANE
Date Installed: Mar 13, 2025
Heating Capacity: 125,000 BTU
Cooling Capacity: 60,000 BTU (5 Ton)
R22 Refrigerant
Installed by Tenant (Info. from Kevin J Bresson, MBA, M.Eng
Director Supply Chain Management)', 43.6820962, -79.6658285, 'GBC060AWEMB0000', '23254733PA', 'TRANE', 'Mar 13, 2025', 2025, '125,000', 5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (2, 1, 'RTU-02', 'Building: 1850 Derry Road East
System: Roof Top Units
Description: RTU-02
Suite: Single Tenant
Model: RGS090SFCA0AATA
Serial: P210544604
Make: ICP
Date Installed: Jan 01, 2021
Heating Capacity: 224,000 BTU
Cooling Capacity: 90,000 BTU (7.5 Ton)
R-22 Refrigerant', 43.681913, -79.6660371, 'RGS090SFCA0AATA', 'P210544604', 'ICP', 'Jan 01, 2021', 2021, '224,000', 7.5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (3, 1, 'RTU-03', 'Building: 1850 Derry Road East
System: Roof Top Units
Description: RTU-03
Suite: Single Tenant
Model: 48ES-A2404030
Serial: 0812C02908
Make: CARRIER
Date Installed: Feb 01, 2012
Heating Capacity: 40,000 BTU
Cooling Capacity: 24,000 BTU (2 Ton)
R-410A Refrigerant', 43.6817908, -79.6660487, '48ES-A2404030', '0812C02908', 'CARRIER', 'Feb 01, 2012', 2012, '40,000', 2, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (4, 1, 'RTU-04', 'Building: 1850 Derry Road East
System: Roof Top Units
Description: RTU-04
Suite: Single Tenant
Model: 48TCEA06A2A1A0B0A0
Serial: 0912C65667
Make: CARRIER
Date Installed: Mar 01, 2012
Heating Data: 115,000 BTU
Cooling Capacity: 60,000 BTU (5 Ton)
R-410A Refrigerant', 43.6818526, -79.6659055, '48TCEA06A2A1A0B0A0', '0912C65667', 'CARRIER', 'Mar 01, 2012', 2012, NULL, 5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (5, 1, 'RTU-05', 'Building: 1850 Derry Road East
System: Roof Top Units
Description: RTU-05
Suite: Single Tenant
Model: PGD430040K000C1
Serial: C102888078
Make: ICP
Date Installed: Jul 01, 2010
Heating Capacity: 70,000 BTU
Cooling Capacity: 30,000 BTU (2.5 Ton)
R22 Refrigerant', 43.6818803, -79.6658799, 'PGD430040K000C1', 'C102888078', 'ICP', 'Jul 01, 2010', 2010, '70,000', 2.5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (6, 1, 'RTU-06 Hybrid', 'Building: 1850 Derry Road East
System: Roof Top Units
Description: RTU-06 Hybrid/Dual Fuel Heat Pump
Suite: Single Tenant
Model: DSK180AWSAH02F0D0A1B✓
Serial: 255010845D✓
Make: TRANE
Date Installed: Jan 15, 2026
Heating Capacity: 400,000 BTU
Cooling Capacity: 180,000 BTU (15 Ton)
R-454B Refrigerant', 43.6820286, -79.6656702, 'DSK180AWSAH02F0D0A1B✓', '255010845D✓', 'TRANE', 'Jan 15, 2026', 2026, '400,000', 15, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (7, 2, 'RTU-01', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-01
Suite: -
Model: 4YCC4036A1070AC
Serial: 212513486L
Make: TRANE
Date Installed: Sep 28, 2021
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)
-updated by Marcus Ganhao August 9, 2023', 43.6656888, -79.6534573, '4YCC4036A1070AC', '212513486L', 'TRANE', 'Sep 28, 2021', 2021, '80,000', 3, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (8, 2, 'RTU-02', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-02
Suite: -
Model: KGA060S4DH4J
Serial: 5615K03130
Make: LENNOX
Date Installed: Nov 18, 2015
Heating Capacity 125,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)
-updated by Marcus Ganhao August 9, 2023', 43.665727, -79.6534415, 'KGA060S4DH4J', '5615K03130', 'LENNOX', 'Nov 18, 2015', 2015, '125,000', 5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (9, 2, 'RTU-03', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-03
Suite: -
Model: ZJ060N10P5AAC1C
Serial: N0N8529315
Make: YORK
Date Installed: Nov 18, 2008
Heating Capacity 125,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)
-updated by Marcus Ganhao August 9, 2023', 43.6658397, -79.6532897, 'ZJ060N10P5AAC1C', 'N0N8529315', 'YORK', 'Nov 18, 2008', 2008, '125,000', 5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (10, 2, 'RTU-04', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-04
Suite: -
Model: GBC048AWEMB07C0
Serial: 21232584PA
Make: TRANE
Date Installed: Sep 28, 2021
Heating Capacity 115,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.6659242, -79.6531849, 'GBC048AWEMB07C0', '21232584PA', 'TRANE', 'Sep 28, 2021', 2021, '115,000', 4, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (11, 2, 'RTU-05', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-05
Suite: -
Model: TGA048S2DH1J
Serial: 5608A01018
Make: LENNOX
Date Installed: Nov 18, 2008
Heating Capacity 150,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.6659988, -79.6531176, 'TGA048S2DH1J', '5608A01018', 'LENNOX', 'Nov 18, 2008', 2008, '150,000', 4, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (12, 2, 'RTU-06', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-06
Suite: -
Model: KGA036S4DM2P
Serial: 5614J02404
Make: LENNOX
Date Installed: Nov 18, 2014
Heating Capacity 105,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6660574, -79.6530391, 'KGA036S4DM2P', '5614J02404', 'LENNOX', 'Nov 18, 2014', 2014, '105,000', 3, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (13, 2, 'RTU-07', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-07
Suite: -
Model: GCS16-030-75-4P
Serial: 5604A10077
Make: LENNOX
Date Installed: Nov 18, 2004
Heating Capacity 60,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)', 43.6661305, -79.6529686, 'GCS16-030-75-4P', '5604A10077', 'LENNOX', 'Nov 18, 2004', 2004, '60,000', 2.5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (14, 2, 'RTU-08', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-08
Suite: -
Model: KGB024S4DW1P
Serial: 5615J07926
Make: LENNOX
Date Installed: Nov 18, 2015
Heating Capacity 65,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.6661902, -79.652884, 'KGB024S4DW1P', '5615J07926', 'LENNOX', 'Nov 18, 2015', 2015, '65,000', 2, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (15, 2, 'RTU-09', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-09
Suite: -
Model: ZJ048N10N5AAA1B
Serial: N0E8884347
Make: YORK
Date Installed: Nov 18, 2008
Heating Capacity 125,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.6662938, -79.6527737, 'ZJ048N10N5AAA1B', 'N0E8884347', 'YORK', 'Nov 18, 2008', 2008, '125,000', 4, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (16, 2, 'RTU-10', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-10
Suite: -
Model: KGB030S4DW1P
Serial: 5615G14365
Make: LENNOX
Date Installed: Nov 18, 2015
Heating Capacity 70,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)', 43.6663863, -79.6526661, 'KGB030S4DW1P', '5615G14365', 'LENNOX', 'Nov 18, 2015', 2015, '70,000', 2.5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (17, 2, 'RTU-11', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-11
Suite: -
Model: KGB024S4DW1P
Serial: 5615H05512
Make: LENNOX
Date Installed: Nov 18, 2015
Heating Capacity 65,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.6664467, -79.6525937, 'KGB024S4DW1P', '5615H05512', 'LENNOX', 'Nov 18, 2015', 2015, '65,000', 2, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (18, 2, 'RTU-12', 'Building: 1645 Bonhill Road
System: Roof Top Units
Description: RTU-12
Suite: -
Model: KGA060S4DH4J
Serial: 5615K03129
Make: LENNOX
Date Installed: Nov 18, 2015
Heating Capacity 125,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.666535, -79.6525565, 'KGA060S4DH4J', '5615K03129', 'LENNOX', 'Nov 18, 2015', 2015, '125,000', 5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (19, 3, 'RTU-01A', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-01A
Suite: SUITE 1
Model: ZF060N10N5AAA1A
Serial: N1M0478065
Make: YORK
Date Installed: Nov 18, 2010
Heating Capacity 125,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6660853, -79.6542279, 'ZF060N10N5AAA1A', 'N1M0478065', 'YORK', 'Nov 18, 2010', 2010, '125,000', 5, 'SUITE 1');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (20, 3, 'RTU-01B', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-01B
Suite: SUITE 1
Model: ZF060N10N5AAA1A
Serial: N1K0360433
Make: YORK
Date Installed: Nov 18, 2010
Heating Capacity 125,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6662239, -79.6543527, 'ZF060N10N5AAA1A', 'N1K0360433', 'YORK', 'Nov 18, 2010', 2010, '125,000', 5, 'SUITE 1');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (21, 3, 'RTU-02', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-02
Suite: SUITE 3
Model: KGA036S4DM2J
Serial: 45613L05029
Make: LENNOX
Date Installed: Nov 01, 2013
Heating Capacity 105,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6663338, -79.654241, 'KGA036S4DM2J', '45613L05029', 'LENNOX', 'Nov 01, 2013', 2013, '105,000', 3, 'SUITE 3');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (22, 3, 'RTU-03', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-03
Suite: SUITE 4
Model: KGA030S4DS2P
Serial: 5614E08039
Make: LENNOX
Date Installed: Nov 18, 2014
Heating Capacity 70,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)', 43.6664011, -79.6541585, 'KGA030S4DS2P', '5614E08039', 'LENNOX', 'Nov 18, 2014', 2014, '70,000', 2.5, 'SUITE 4');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (23, 3, 'RTU-04', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-04
Suite: SUITE 5
Model: 48VL-E2406030
Serial: 4022F50128
Make: CARRIER
Date Installed: Oct 28, 2022
Heating Capacity 60,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.6664783, -79.6540995, '48VL-E2406030', '4022F50128', 'CARRIER', 'Oct 28, 2022', 2022, '60,000', 2, 'SUITE 5');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (24, 3, 'RTU-05', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-05
Suite: SUITE 6
Model: ZJ048N10N5AAA1B
Serial: N0H8207771
Make: YORK
Date Installed: Nov 18, 2008
Heating Capacity 125,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.6665531, -79.653992, 'ZJ048N10N5AAA1B', 'N0H8207771', 'YORK', 'Nov 18, 2008', 2008, '125,000', 4, 'SUITE 6');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (25, 3, 'RTU-06', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-06
Suite: Suite 8
Model: D3NZ030N05606A
Serial: N0L9302666
Make: YORK
Date Installed: Nov 18, 2009
Heating Capacity 70,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)', 43.66667, -79.6538903, 'D3NZ030N05606A', 'N0L9302666', 'YORK', 'Nov 18, 2009', 2009, '70,000', 2.5, 'Suite 8');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (26, 3, 'RTU-07', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-07
Suite: Suite 9
Model: KGB036S4EW3P
Serial: 5623J07963
Make: LENNOX
Date Installed: Oct 10, 2023
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6667368, -79.6537701, 'KGB036S4EW3P', '5623J07963', 'LENNOX', 'Oct 10, 2023', 2023, '80,000', 3, 'Suite 9');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (27, 3, 'RTU-08', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-08
Suite: SUITE 10
Model: 48VL - F3006030
Serial: 3622F50582
Make: CARRIER
Date Installed: Oct 28, 2022
Heating Capacity 70,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)', 43.6667744, -79.6537304, '48VL - F3006030', '3622F50582', 'CARRIER', 'Oct 28, 2022', 2022, '70,000', 2.5, 'SUITE 10');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (28, 3, 'RTU-09', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-09
Suite: SUITE 11
Model: D2NZ024N05606A
Serial: N0G8147080
Make: YORK
Date Installed: Nov 18, 2008
Heating Capacity 60,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.6668666, -79.6536563, 'D2NZ024N05606A', 'N0G8147080', 'YORK', 'Nov 18, 2008', 2008, '60,000', 2, 'SUITE 11');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (29, 3, 'RTU-10', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-10
Suite: Suite 12
Model: 4YCC4024A1060AC
Serial: 212910341L
Make: TRANE
Date Installed: Aug 19, 2021
Heating Capacity 60,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.6669254, -79.653591, '4YCC4024A1060AC', '212910341L', 'TRANE', 'Aug 19, 2021', 2021, '60,000', 2, 'Suite 12');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (30, 3, 'RTU-11', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-11
Suite: SUITE 13
Model: KGA036S4DM2P
Serial: 5614F02241
Make: LENNOX
Date Installed: Nov 18, 2014
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6669939, -79.6534791, 'KGA036S4DM2P', '5614F02241', 'LENNOX', 'Nov 18, 2014', 2014, '80,000', 3, 'SUITE 13');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (31, 3, 'RTU-12', 'Building: 1680 Courtneypark Drive
System: Roof Top Units
Description: RTU-12
Suite: SUITE 14
Model: ZF036N08N1AAA1A
Serial: N1N0579615
Make: LENNOX
Date Installed: Nov 18, 2010
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6670511, -79.6534187, 'ZF036N08N1AAA1A', 'N1N0579615', 'LENNOX', 'Nov 18, 2010', 2010, '80,000', 3, 'SUITE 14');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (32, 4, 'RTU-01', 'Building: 1695 Bonhill Road
System: Roof Top Units
Description: RTU-01
Suite: Single Tenant
Model: DF090N15N5AAA4B
Serial: N0F8019975
Make: YORK
Date Installed: Nov 18, 2008
Heating Capacity 180,000 BTU''s
Cooling Capacity: 90,000 BTU (7.5 Ton)', 43.6668866, -79.6520367, 'DF090N15N5AAA4B', 'N0F8019975', 'YORK', 'Nov 18, 2008', 2008, '180,000', 7.5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (33, 5, 'RTU-01', 'Building: 1700 Courtneypark Drive
System: Roof Top Units
Description: RTU-01
Suite: -
Model: ZJ060D10N5ABA1C
Serial: N0N8495339
Make: YORK
Date Installed: Nov 19, 2008
Heating Capacity 100,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.667304, -79.653209, 'ZJ060D10N5ABA1C', 'N0N8495339', 'YORK', 'Nov 19, 2008', 2008, '100,000', 5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (34, 5, 'RTU-02', 'Building: 1700 Courtneypark Drive
System: Roof Top Units
Description: RTU-02
Suite: -
Model: ZJ060D10N5ABA1C
Serial: N0K8289080
Make: YORK
Date Installed: Nov 19, 2008
Heating Capacity 100,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6674174, -79.6530746, 'ZJ060D10N5ABA1C', 'N0K8289080', 'YORK', 'Nov 19, 2008', 2008, '100,000', 5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (35, 5, 'RTU-03', 'Building: 1700 Courtneypark Drive
System: Roof Top Units
Description: RTU-03
Suite: -
Model: ZJ060D10N5ABA1C
Serial: N0H8236133
Make: YORK
Date Installed: Nov 19, 2008
Heating Capacity 100,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6675741, -79.6529421, 'ZJ060D10N5ABA1C', 'N0H8236133', 'YORK', 'Nov 19, 2008', 2008, '100,000', 5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (36, 5, 'RTU-04', 'Building: 1700 Courtneypark Drive
System: Roof Top Units
Description: RTU-04
Suite: -
Model: PCG4A240752X1A
Serial: W1M6191334
Make: YORK
Date Installed: Nov 19, 2016
Heating Input: 75,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.6675234, -79.6528067, 'PCG4A240752X1A', 'W1M6191334', 'YORK', 'Nov 19, 2016', 2016, NULL, 2, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (37, 6, 'RTU-01', 'Building: 1745 Bonhill Road
System: Roof Top Units
Description: RTU-01
Suite: SUITE 1&2
Model: 48FCEA06A2A1A0A0A0
Serial: 3219C89954
Make: CARRIER
Date Installed: Nov 18, 2019
Heating Capacity 110,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)
Unit 1 & 2', 43.667322, -79.6515354, '48FCEA06A2A1A0A0A0', '3219C89954', 'CARRIER', 'Nov 18, 2019', 2019, '110,000', 5, 'SUITE 1&2');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (38, 6, 'RTU-02', 'Building: 1745 Bonhill Road
System: Roof Top Units
Description: RTU-02
Suite: SUITE 3
Model: ZJ036N08N1AAA1C
Serial: N0L8443228
Make: YORK
Date Installed: Nov 18, 2008
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)
Unit 3', 43.6674732, -79.6513203, 'ZJ036N08N1AAA1C', 'N0L8443228', 'YORK', 'Nov 18, 2008', 2008, '80,000', 3, 'SUITE 3');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (39, 6, 'RTU-03', 'Building: 1745 Bonhill Road
System: Roof Top Units
Description: RTU-03
Suite: SUITE 4
Model: D2NZ030D05606A
Serial: N0D8793940
Make: YORK
Date Installed: Nov 18, 2008
Heating Capacity 70,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)
Unit 4', 43.6675435, -79.6512398, 'D2NZ030D05606A', 'N0D8793940', 'YORK', 'Nov 18, 2008', 2008, '70,000', 2.5, 'SUITE 4');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (40, 6, 'RTU-04', 'Building: 1745 Bonhill Road
System: Roof Top Units
Description: RTU-04
Suite: SUITE 5
Model: D2NZ030N05606A
Serial: N0F9944531
Make: YORK
Date Installed: Nov 18, 2009
Heating Capacity 70,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)
Unit 5', 43.6676611, -79.6511343, 'D2NZ030N05606A', 'N0F9944531', 'YORK', 'Nov 18, 2009', 2009, '70,000', 2.5, 'SUITE 5');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (41, 6, 'RTU-05', 'Building: 1745 Bonhill Road
System: Roof Top Units
Description: RTU-05
Suite: SUITE 6&7
Model: ZJ060D10N5ABA1C
Serial: N0E9806364
Make: YORK
Date Installed: Nov 18, 2009
Heating Capacity 125,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)
Unit 6 & 7', 43.6677634, -79.6510394, 'ZJ060D10N5ABA1C', 'N0E9806364', 'YORK', 'Nov 18, 2009', 2009, '125,000', 5, 'SUITE 6&7');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (42, 6, 'RTU-06', 'Building: 1745 Bonhill Road
System: Roof Top Units
Description: RTU-06
Suite: Suite 8
Model: KGA036S4BM2J
Serial: 5613J04311
Make: LENNOX
Date Installed: Nov 18, 2013
Heating Capacity 108,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)
Unit 8', 43.6679027, -79.6508883, 'KGA036S4BM2J', '5613J04311', 'LENNOX', 'Nov 18, 2013', 2013, '108,000', 3, 'Suite 8');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (43, 7, 'RTU-06', 'Building: 1750 Courtneypark Drive
System: Roof Top Units
Description: RTU-06
Suite: -
Model: KGA048S4DH2J
Serial: 5614E02351
Make: LENNOX
Date Installed: Nov 19, 2014
Heating Capacity 150,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.6684916, -79.6518879, 'KGA048S4DH2J', '5614E02351', 'LENNOX', 'Nov 19, 2014', 2014, '150,000', 4, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (44, 7, 'RTU-05', 'Building: 1750 Courtneypark Drive
System: Roof Top Units
Description: RTU-05
Suite: -
Model: ZJ048N10N5AAA1C
Serial: N0N9463827
Make: YORK
Date Installed: Nov 19, 2009
Heating Capacity 100,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.6683771, -79.6520514, 'ZJ048N10N5AAA1C', 'N0N9463827', 'YORK', 'Nov 19, 2009', 2009, '100,000', 4, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (45, 7, 'RTU-04', 'Building: 1750 Courtneypark Drive
System: Roof Top Units
Description: RTU-04
Suite: -
Model: KGA030S4DS2P
Serial: 5612A03796
Make: LENNOX
Date Installed: Nov 19, 2012
Heating Capacity 65,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)', 43.6682528, -79.6521654, 'KGA030S4DS2P', '5612A03796', 'LENNOX', 'Nov 19, 2012', 2012, '65,000', 2.5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (46, 7, 'RTU-03', 'Building: 1750 Courtneypark Drive
System: Roof Top Units
Description: RTU-03
Suite: -
Model: KGA036S4BM2Y
Serial: 5614E05293
Make: LENNOX
Date Installed: Nov 19, 2014
Heating Capacity 105,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6681581, -79.6522823, 'KGA036S4BM2Y', '5614E05293', 'LENNOX', 'Nov 19, 2014', 2014, '105,000', 3, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (47, 7, 'RTU-02', 'Building: 1750 Courtneypark Drive
System: Roof Top Units
Description: RTU-02
Suite: -
Model: KGA060S4DH3J
Serial: 5614E08217
Make: LENNOX
Date Installed: Nov 19, 2014
Heating Capacity 150,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6680267, -79.6524272, 'KGA060S4DH3J', '5614E08217', 'LENNOX', 'Nov 19, 2014', 2014, '150,000', 5, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (48, 7, 'RTU-01', 'Building: 1750 Courtneypark Drive
System: Roof Top Units
Description: RTU-01
Suite: -
Model: KGA048S4DH2P
Serial: 5614E05387
Make: LENNOX
Date Installed: Nov 19, 2014
Heating Capacity 150,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.6678937, -79.6525557, 'KGA048S4DH2P', '5614E05387', 'LENNOX', 'Nov 19, 2014', 2014, '150,000', 4, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (49, 8, 'RTU-06', 'Building: 1775 Bonhill Road
System: Roof Top Units
Description: RTU-06
Suite: Single Tenant
Model: ZF036N08N2AAA1A
Serial: N1D0757604
Make: YORK
Date Installed: Nov 18, 2010
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6685683, -79.6500544, 'ZF036N08N2AAA1A', 'N1D0757604', 'YORK', 'Nov 18, 2010', 2010, '80,000', 3, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (50, 8, 'RTU-05', 'Building: 1775 Bonhill Road
System: Roof Top Units
Description: RTU-05
Suite: Single Tenant
Model: ZF036N08N2AAA1A
Serial: N1C0713647
Make: YORK
Date Installed: Nov 18, 2010
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6684947, -79.6501113, 'ZF036N08N2AAA1A', 'N1C0713647', 'YORK', 'Nov 18, 2010', 2010, '80,000', 3, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (51, 8, 'RTU-04', 'Building: 1775 Bonhill Road
System: Roof Top Units
Description: RTU-04
Suite: Single Tenant
Model: ZF036N08N1AAA1A
Serial: N1D0767839
Make: YORK
Date Installed: Nov 18, 2010
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6683169, -79.6503124, 'ZF036N08N1AAA1A', 'N1D0767839', 'YORK', 'Nov 18, 2010', 2010, '80,000', 3, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (52, 8, 'RTU-03', 'Building: 1775 Bonhill Road
System: Roof Top Units
Description: RTU-03
Suite: Single Tenant
Model: ZJ060N10N5AAA1B
Serial: N0D8805561
Make: YORK
Date Installed: Nov 18, 2008
Heating Capacity 100,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6682156, -79.6504424, 'ZJ060N10N5AAA1B', 'N0D8805561', 'YORK', 'Nov 18, 2008', 2008, '100,000', 5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (53, 8, 'RTU-02', 'Building: 1775 Bonhill Road
System: Roof Top Units
Description: RTU-02
Suite: Single Tenant
Model: ZF060N10N5AAA1A
Serial: N1G0113838
Make: YORK
Date Installed: Nov 18, 2010
Heating Capacity 100,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6681468, -79.6505158, 'ZF060N10N5AAA1A', 'N1G0113838', 'YORK', 'Nov 18, 2010', 2010, '100,000', 5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (54, 8, 'RTU-01', 'Building: 1775 Bonhill Road
System: Roof Top Units
Description: RTU-01
Suite: Single Tenant
Model: D3NZ030N05606A
Serial: N0L9302662
Make: YORK
Date Installed: Nov 18, 2009
Heating Capacity 56,000 BTU''s
Cooling Capacity: 30,000 BTU (2.5 Ton)', 43.6680783, -79.6506069, 'D3NZ030N05606A', 'N0L9302662', 'YORK', 'Nov 18, 2009', 2009, '56,000', 2.5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (55, 9, 'RTU-05', 'Building: 1800 Courtneypark Drive
System: Roof Top Units
Description: RTU-05
Suite: -
Model: ZF048H12B5A1ABA1A1A
Serial: N1N6252353
Make: YORK
Date Installed: Nov 19, 2016
Heating Capacity 125,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.669177, -79.6511518, 'ZF048H12B5A1ABA1A1A', 'N1N6252353', 'YORK', 'Nov 19, 2016', 2016, '125,000', 4, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (56, 9, 'RTU-04', 'Building: 1800 Courtneypark Drive
System: Roof Top Units
Description: RTU-04
Suite: -
Model: PCG4A240752X1A
Serial: W1C7582115
Make: YORK
Date Installed: Nov 19, 2017
Heating Capacity 75,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.6689455, -79.6513602, 'PCG4A240752X1A', 'W1C7582115', 'YORK', 'Nov 19, 2017', 2017, '75,000', 2, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (57, 9, 'RTU-03', 'Building: 1800 Courtneypark Drive
System: Roof Top Units
Description: RTU-03
Suite: -
Model: GBC048AWEMB07C
Serial: 21212601PA
Make: TRANE
Date Installed: Sep 28, 2021
Heating Capacity 125,000 BTU''s
Cooling Capacity: 48,000 BTU (4 Ton)', 43.6689042, -79.6514345, 'GBC048AWEMB07C', '21212601PA', 'TRANE', 'Sep 28, 2021', 2021, '125,000', 4, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (58, 9, 'RTU-02', 'Building: 1800 Courtneypark Drive
System: Roof Top Units
Description: RTU-02
Suite: -
Model: KGA036S4DM3Y
Serial: 5615F07015
Make: LENNOX
Date Installed: Nov 19, 2015
Heating Capacity 108,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6686953, -79.6516404, 'KGA036S4DM3Y', '5615F07015', 'LENNOX', 'Nov 19, 2015', 2015, '108,000', 3, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (59, 9, 'RTU-01', 'Building: 1800 Courtneypark Drive
System: Roof Top Units
Description: RTU-01
Suite: -
Model: KGB024S4DW1P
Serial: 5615F09907
Make: LENNOX
Date Installed: Nov 19, 2015
Heating Capacity 65,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.668653, -79.6516163, 'KGB024S4DW1P', '5615F09907', 'LENNOX', 'Nov 19, 2015', 2015, '65,000', 2, '-');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (60, 10, 'RTU-01', 'Building: 1820 Courtneypark Drive
System: Roof Top Units
Description: RTU-01
Suite: Single Tenant
Model: ZF036N08N2AAA2A
Serial: N1C3553040
Make: YORK
Date Installed: Nov 19, 2013
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6694904, -79.6506947, 'ZF036N08N2AAA2A', 'N1C3553040', 'YORK', 'Nov 19, 2013', 2013, '80,000', 3, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (61, 10, 'RTU-02', 'Building: 1820 Courtneypark Drive
System: Roof Top Units
Description: RTU-02
Suite: Single Tenant
Model: ZJ060N10N5AAA1B
Serial: N0D8805562
Make: YORK
Date Installed: Nov 19, 2008
Heating Capacity 100,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6695537, -79.6506154, 'ZJ060N10N5AAA1B', 'N0D8805562', 'YORK', 'Nov 19, 2008', 2008, '100,000', 5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (62, 10, 'RTU-03', 'Building: 1820 Courtneypark Drive
System: Roof Top Units
Description: RTU-03
Suite: Single Tenant
Model: ZF072N10N5AAA1A
Serial: N1E3756096
Make: YORK
Date Installed: Nov 19, 2013
Heating Capacity 125,000 BTU''s
Cooling Capacity: 72,000 BTU (6 Ton)', 43.6695391, -79.6505746, 'ZF072N10N5AAA1A', 'N1E3756096', 'YORK', 'Nov 19, 2013', 2013, '125,000', 6, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (63, 10, 'RTU-04', 'Building: 1820 Courtneypark Drive
System: Roof Top Units
Description: RTU-04
Suite: Single Tenant
Model: ZF090N15N2AAA5A
Serial: N1D3653884
Make: YORK
Date Installed: Nov 19, 2013
Heating Capacity 180,000 BTU''s
Cooling Capacity: 90,000 BTU (7.5 Ton)', 43.669579, -79.6505694, 'ZF090N15N2AAA5A', 'N1D3653884', 'YORK', 'Nov 19, 2013', 2013, '180,000', 7.5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (64, 10, 'RTU-05', 'Building: 1820 Courtneypark Drive
System: Roof Top Units
Description: RTU-05
Suite: Single Tenant
Model: ZJ060N10N5AAA1B
Serial: N0D8805563
Make: YORK
Date Installed: Nov 19, 2008
Heating Capacity 125,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6696795, -79.6504539, 'ZJ060N10N5AAA1B', 'N0D8805563', 'YORK', 'Nov 19, 2008', 2008, '125,000', 5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (65, 10, 'RTU-06', 'Building: 1820 Courtneypark Drive
System: Roof Top Units
Description: RTU-06
Suite: Single Tenant
Model: ZF060N10N5AAA2A
Serial: N1B3491413
Make: YORK
Date Installed: Nov 19, 2013
Heating Capacity 125,000 BTU''s
Cooling Capacity: 60,000 BTU (5 Ton)', 43.6697198, -79.6504211, 'ZF060N10N5AAA2A', 'N1B3491413', 'YORK', 'Nov 19, 2013', 2013, '125,000', 5, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (66, 10, 'RTU-07', 'Building: 1820 Courtneypark Drive
System: Roof Top Units
Description: RTU-07
Suite: Single Tenant
Model: ZF036N08N2AAA2A
Serial: N1C3553039
Make: YORK
Date Installed: Nov 19, 2013
Heating Capacity 80,000 BTU''s
Cooling Capacity: 36,000 BTU (3 Ton)', 43.6697678, -79.6503534, 'ZF036N08N2AAA2A', 'N1C3553039', 'YORK', 'Nov 19, 2013', 2013, '80,000', 3, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (67, 11, 'RTU-01', 'Building: 1840 Courtneypark Drive
System: Roof Top Units
Description: RTU-01
Suite: Single Tenant
Model: D2NZ024N05606A
Serial: N0A9569971
Make: YORK
Date Installed: Nov 19, 2009
Heating Capacity 60,000 BTU''s
Cooling Capacity: 24,000 BTU (2 Ton)', 43.6701244, -79.6499831, 'D2NZ024N05606A', 'N0A9569971', 'YORK', 'Nov 19, 2009', 2009, '60,000', 2, 'Single Tenant');
INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (68, 11, 'RTU-05', 'Building: 1840 Courtneypark Drive
System: Roof Top Units
Description: RTU-05
Suite: Single Tenant
Model: KGB024S4DW1P
Serial: 5615F03332
Make: LENNOX
Date Installed: Nov 19, 2015