/**
 * Bump deploy version stamp: vYYYY.MM.DD (n).
 * Same calendar day (UTC) increments n; a new day resets n to 1.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const VERSION_FILE = join(ROOT, 'version.build.json')
const OUT_TS = join(ROOT, 'src', 'generated', 'buildVersion.ts')

function formatDateUtc(date) {
  const y = date.getUTCFullYear()
  const m = String(date.getUTCMonth() + 1).padStart(2, '0')
  const d = String(date.getUTCDate()).padStart(2, '0')
  return `${y}.${m}.${d}`
}

const today = formatDateUtc(new Date())
let data = { date: today, build: 0 }

try {
  data = JSON.parse(readFileSync(VERSION_FILE, 'utf8'))
} catch {
  /* first run */
}

if (data.date === today) {
  data.build = Number(data.build) + 1
} else {
  data.date = today
  data.build = 1
}

writeFileSync(VERSION_FILE, `${JSON.stringify(data, null, 2)}\n`)

const label = `v${data.date} (${data.build})`
mkdirSync(dirname(OUT_TS), { recursive: true })
writeFileSync(
  OUT_TS,
  `/** Generated by scripts/bump-version.mjs — do not edit */\nexport const BUILD_VERSION_LABEL = '${label}'\nexport const BUILD_VERSION: { date: string; build: number } = ${JSON.stringify(data)}\n`,
)

console.log(`Version stamp: ${label}`)
