/**
 * Parses BUILDINGS, UTILITIES, and POLYGONS from the legacy single-file HTML
 * and emits supabase/seed.sql plus JSON snapshots under supabase/data/.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const DEFAULT_HTML = join(
  process.env.HOME ?? process.env.USERPROFILE ?? '',
  'Downloads',
  'building_map_explorer_v2026_06_20_3.html',
)
const HTML_PATH = process.argv[2] ?? DEFAULT_HTML

interface LegacyRtu {
  name: string
  desc: string
  lat: number
  lng: number
}

interface LegacyTenant {
  name: string
  desc?: string
  lat: number
  lng: number
}

interface LegacyBuilding {
  park: string
  address: string
  bu: string
  lat: number
  lng: number
  sqft: string
  cluster: string
  manager: string
  notes?: string
  rtus?: LegacyRtu[]
  tenants?: LegacyTenant[]
}

interface LegacyUtility {
  type: string
  name: string
  desc: string
  lat: number
  lng: number
}

interface LegacyPolygon {
  name: string
  desc: string
  color: string
  paths: { lat: number; lng: number }[]
}

function extractArray<T>(html: string, varName: string): T[] {
  const marker = `const ${varName} = `
  const start = html.indexOf(marker)
  if (start === -1) throw new Error(`Could not find ${varName} in HTML`)
  let i = start + marker.length
  if (html[i] !== '[') throw new Error(`${varName} is not an array`)
  const begin = i
  let depth = 0
  let inString = false
  let escape = false
  for (; i < html.length; i++) {
    const ch = html[i]!
    if (escape) {
      escape = false
      continue
    }
    if (inString) {
      if (ch === '\\') escape = true
      else if (ch === '"') inString = false
      continue
    }
    if (ch === '"') {
      inString = true
      continue
    }
    if (ch === '[') depth++
    else if (ch === ']') {
      depth--
      if (depth === 0) {
        const json = html.slice(begin, i + 1)
        try {
          return JSON.parse(json) as T[]
        } catch {
          return JSON.parse(json.replace(/\u2713/g, '')) as T[]
        }
      }
    }
  }
  throw new Error(`Unterminated array for ${varName}`)
}

function parseRtuDesc(desc: string) {
  const get = (re: RegExp) => {
    const m = desc.match(re)
    return m?.[1]?.trim() ?? null
  }
  const installMatch = desc.match(/Date Installed[:\s]+(?:[A-Za-z]+ +\d+, +)?(\d{4})/i)
  const tonsMatch = desc.match(/\(\s*([\d.]+)\s*ton/i)
  const btuMatch = desc.match(/Cooling Capacity[:\s]*([\d,]+)\s*BTU/i)
  let coolingTons: number | null = tonsMatch ? parseFloat(tonsMatch[1]!) : null
  if (coolingTons == null && btuMatch) {
    const btu = parseInt(btuMatch[1]!.replace(/,/g, ''), 10)
    if (btu) coolingTons = Math.round((btu / 12000) * 10) / 10
  }
  return {
    model: get(/Model[:\s]+(.+?)(?:\r|\n|$)/i),
    serial: get(/Serial[:\s]+(.+?)(?:\r|\n|$)/i),
    make: get(/Make[:\s]+(.+?)(?:\r|\n|$)/i),
    install_date: get(/Date Installed[:\s]+(.+?)(?:\r|\n|$)/i),
    install_year: installMatch ? parseInt(installMatch[1]!, 10) : null,
    heating_btu: get(/Heating Capacity[:\s]+([\d,]+)\s*BTU/i),
    cooling_tons: coolingTons,
    suite: get(/Suite[:\s]+(.+?)(?:\r|\n|$)/i),
  }
}

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''")
}

function main() {
  console.log(`Reading ${HTML_PATH}`)
  const html = readFileSync(HTML_PATH, 'utf8')
  const buildings = extractArray<LegacyBuilding>(html, 'BUILDINGS')
  const utilities = extractArray<LegacyUtility>(html, 'UTILITIES')
  const polygons = extractArray<LegacyPolygon>(html, 'POLYGONS')

  const dataDir = join(ROOT, 'supabase', 'data')
  mkdirSync(dataDir, { recursive: true })

  writeFileSync(join(dataDir, 'buildings.json'), JSON.stringify(buildings, null, 2))
  writeFileSync(join(dataDir, 'utilities.json'), JSON.stringify(utilities, null, 2))
  writeFileSync(join(dataDir, 'polygons.json'), JSON.stringify(polygons, null, 2))

  const lines: string[] = [
    '-- Generated by scripts/extract.ts — do not edit by hand',
    'BEGIN;',
    'TRUNCATE rtus, tenants, buildings, utilities, polygons, app_settings RESTART IDENTITY CASCADE;',
  ]

  const buildingIdByAddress = new Map<string, number>()
  buildings.forEach((b, idx) => {
    const id = idx + 1
    buildingIdByAddress.set(b.address, id)
    lines.push(
      `INSERT INTO buildings (id, park, address, bu, lat, lng, sqft, cluster, manager, notes) VALUES (${id}, '${sqlEscape(b.park)}', '${sqlEscape(b.address)}', '${sqlEscape(b.bu ?? '')}', ${b.lat}, ${b.lng}, '${sqlEscape(b.sqft ?? '')}', '${sqlEscape(b.cluster ?? '')}', '${sqlEscape(b.manager ?? '')}', ${b.notes ? `'${sqlEscape(b.notes)}'` : 'NULL'});`,
    )
  })

  let rtuId = 1
  for (const b of buildings) {
    const buildingId = buildingIdByAddress.get(b.address)!
    for (const r of b.rtus ?? []) {
      const parsed = parseRtuDesc(r.desc ?? '')
      lines.push(
        `INSERT INTO rtus (id, building_id, name, description, lat, lng, model, serial, make, install_date, install_year, heating_btu, cooling_tons, suite) VALUES (${rtuId++}, ${buildingId}, '${sqlEscape(r.name)}', '${sqlEscape(r.desc ?? '')}', ${r.lat}, ${r.lng}, ${parsed.model ? `'${sqlEscape(parsed.model)}'` : 'NULL'}, ${parsed.serial ? `'${sqlEscape(parsed.serial)}'` : 'NULL'}, ${parsed.make ? `'${sqlEscape(parsed.make)}'` : 'NULL'}, ${parsed.install_date ? `'${sqlEscape(parsed.install_date)}'` : 'NULL'}, ${parsed.install_year ?? 'NULL'}, ${parsed.heating_btu ? `'${sqlEscape(parsed.heating_btu)}'` : 'NULL'}, ${parsed.cooling_tons ?? 'NULL'}, ${parsed.suite ? `'${sqlEscape(parsed.suite)}'` : 'NULL'});`,
      )
    }
  }

  let tenantId = 1
  for (const b of buildings) {
    const buildingId = buildingIdByAddress.get(b.address)!
    for (const t of b.tenants ?? []) {
      lines.push(
        `INSERT INTO tenants (id, building_id, name, description, lat, lng) VALUES (${tenantId++}, ${buildingId}, '${sqlEscape(t.name)}', '${sqlEscape(t.desc ?? '')}', ${t.lat}, ${t.lng});`,
      )
    }
  }

  utilities.forEach((u, idx) => {
    lines.push(
      `INSERT INTO utilities (id, utility_type, name, description, lat, lng) VALUES (${idx + 1}, '${sqlEscape(u.type)}', '${sqlEscape(u.name)}', '${sqlEscape(u.desc ?? '')}', ${u.lat}, ${u.lng});`,
    )
  })

  polygons.forEach((p, idx) => {
    lines.push(
      `INSERT INTO polygons (id, name, description, color, paths) VALUES (${idx + 1}, '${sqlEscape(p.name)}', '${sqlEscape(p.desc ?? '')}', '${sqlEscape(p.color)}', '${sqlEscape(JSON.stringify(p.paths))}'::jsonb);`,
    )
  })

  lines.push(
    `INSERT INTO app_settings (key, value) VALUES ('theme', '{"name":"default"}'::jsonb);`,
    `INSERT INTO app_settings (key, value) VALUES ('managers', '[]'::jsonb);`,
    'COMMIT;',
  )

  writeFileSync(join(ROOT, 'supabase', 'seed.sql'), lines.join('\n'))
  console.log(
    `Extracted ${buildings.length} buildings, ${utilities.length} utilities, ${polygons.length} polygons`,
  )
}

main()
